# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the rv32-dev branch
  push:
    branches: [ RV32G ]
  pull_request:
    branches: [ RV32G ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: git clone depot_tools
        run: git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: fetch v8
        run: PATH=$PATH:$GITHUB_WORKSPACE/depot_tools fetch v8
    
      - working-directory: ./v8
        run: git remote add riscv https://github.com/riscv-collab/v8.git

      - working-directory: ./v8
        run: git fetch riscv $GITHUB_SHA:LocalCI
 
      - working-directory: ./v8
        run: git checkout LocalCI

      - working-directory: ./v8
        run: echo $GITHUB_REF && echo $GITHUB_SHA &&  git log -1

      - name: presubmit
        working-directory: ./v8
        run: PATH=$PATH:$GITHUB_WORKSPACE/depot_tools git cl presubmit

